StudentPortal/Entities/Curso.cs
namespace StudentPortal.Entities
{
    public class Curso
    {
        public int CursoId { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
        public int Creditos { get; set; } 
        public bool EsObligatorio { get; set; }
        public string Sede { get; set; }
        public int Aula { get; set; }
        public string Horarios { get; set; }
        public int CantInscriptos { get; set; }
        public int MaxInscriptos { get; set; }
        public string Descripcion { get; set; }
        public string Duracion { get; set; }

        public int CalificacionId { get; set; }
        public Calificacion Calificacion { get; set; }

        public int ProfesorId { get; set; } 
        public Profesor Profesor { get; set; }

        public List<CursoEstudiante> CursosEstudiantes { get; set; } = new List<CursoEstudiante>();
    }
}

StudentPortal/Controllers/CursoController.cs
using Microsoft.AspNetCore.Cors.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using StudentPortal.Entities;
using StudentPortal.Services;

namespace StudentPortal.Controllers
{
    public class CursoController : Controller
    {
        private readonly CursoService _cursoService;
        const string SessionUserId = "_UserId";
        const string SessionUserName = "_UserName";

        public CursoController(CursoService cursoService)
        {
            _cursoService = cursoService;
        }

        [HttpGet]
        public async Task<IActionResult> Listar(
            string? busquedaNombre = null,
            string? sede = null,
            int? creditos = null,
            bool? obligatorio = null,
            string? duracion = null,
            int? pagina = 1
        ) {
            var resultado = await _cursoService.ObtenerCursosPaginados(
                pagina: pagina.Value,
                busquedaNombre: busquedaNombre,
                sede: sede,
                creditos: creditos,
                obligatorio: obligatorio,
                duracion: duracion
            );
            return View(resultado);
        }

        [HttpGet("Curso/Estudiante/{estudianteId}")]
        public async Task<IActionResult> ListarCursosPorEstudianteId(int estudianteId) {

            var cursos = await _cursoService.ObtenerCursosPorEstudianteIdAsync(estudianteId);
            
            if (cursos == null) { 
                return RedirectToAction("Index","Home");
            }

            ViewBag.UserId = estudianteId;
            return View("CursosPorEstudiante", cursos);
        }

        [HttpPost]
        public async Task<IActionResult> Inscribir(int cursoId) {
            var resultado = await _cursoService.AsignarEstudianteACursoAsync(cursoId);
            if (resultado == null) {
                ViewBag.Mensaje = "Error al inscribirse";
                return RedirectToAction("Listar");
            }

            ViewBag.Mensaje = "Se inscribió correctamente";
            return RedirectToAction("ListarCursosPorEstudianteId", new { estudianteId = resultado.EstudianteId });
        }

        [HttpPost]
        public async Task<IActionResult> Desinscribir(int cursoId, int estudianteId) {
            
            var resultado = await _cursoService.DesasignarEstudianteDeCursoAsync(cursoId, estudianteId);
            if (!resultado) {

                ViewBag.Mensaje = "Error al desinscribirse";
                return RedirectToAction("Listar");
            }

            ViewBag.Mensaje = "Se desinscribió correctamente";
            return RedirectToAction("ListarCursosPorEstudianteId", new { estudianteId = estudianteId });
        }
    }
}

StudentPortal/Views/Curso/CursosPorEstudiante.cshtml
@using StudentPortal.Entities
@model List<Curso>
@{
    ViewData["Title"] = "Cursos Por Estudiante";
}

<div class="container">
    <div class="row mt-3">
        <div class="col-3">
            @await Html.PartialAsync("_MenuPartialView")
        </div>
        <div class="col-9">
            <div class="row align-items-center mb-2">
                <h3>Mis Cursos</h3>
            </div>
            @*List*@
            <div class="row mb-3 mb-sm-0">
                @foreach (var curso in Model)
                {
                    <div class="col-sm-6 mb-3">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">@curso.Nombre  <span class="badge bg-secondary text-bg-primary">@curso.Codigo</span></h5>
                                <p class="card-text">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                                        <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10m0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6" />
                                    </svg>
                                    Sede: @curso.Sede
                                </p>
                                <p class="card-text">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building-fill" viewBox="0 0 16 16">
                                        <path d="M3 0a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h3v-3.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V16h3a1 1 0 0 0 1-1V1a1 1 0 0 0-1-1zm1 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5M4 5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM7.5 5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5m2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM4.5 8h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5m2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5" />
                                    </svg>
                                    Aula: @curso.Aula
                                </p>
                                <p class="card-text">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-vcard-fill" viewBox="0 0 16 16">
                                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm9 1.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 0-1h-4a.5.5 0 0 0-.5.5M9 8a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 0-1h-4A.5.5 0 0 0 9 8m1 2.5a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 0-1h-3a.5.5 0 0 0-.5.5m-1 2C9 10.567 7.21 9 5 9c-2.086 0-3.8 1.398-3.984 3.181A1 1 0 0 0 2 13h6.96q.04-.245.04-.5M7 6a2 2 0 1 0-4 0 2 2 0 0 0 4 0" />
                                    </svg>
                                    Profesor: @curso.Profesor.Nombre @curso.Profesor.Apellido
                                </p>
                                <p class="card-text">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock-fill" viewBox="0 0 16 16">
                                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71z" />
                                    </svg>
                                    Horarios: @curso.Horarios
                                </p>
                                @*Opciones*@
                                <form method="post" class="d-flex justify-content-end" asp-action="Desinscribir" asp-controller="Curso">
                                    <input name="cursoId" value="@curso.CursoId" hidden />
                                    <input name="estudianteId" value="@ViewBag.UserId" hidden />
                                    <button class="btn btn-dark text-white" type="submit"
                                            data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Desinscribir">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-octagon" viewBox="0 0 16 16">
                                            <path d="M4.54.146A.5.5 0 0 1 4.893 0h6.214a.5.5 0 0 1 .353.146l4.394 4.394a.5.5 0 0 1 .146.353v6.214a.5.5 0 0 1-.146.353l-4.394 4.394a.5.5 0 0 1-.353.146H4.893a.5.5 0 0 1-.353-.146L.146 11.46A.5.5 0 0 1 0 11.107V4.893a.5.5 0 0 1 .146-.353zM5.1 1 1 5.1v5.8L5.1 15h5.8l4.1-4.1V5.1L10.9 1z" />
                                            <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708" />
                                        </svg>
                                        Desinscribir
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>