StudentPortal/Entities/Estudiante.cs
using StudentPortal.Models;

namespace StudentPortal.Entities
{
    public class Estudiante
    {
        public int EstudianteId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Username { get; set; }

        public string Correo { get; set; }
        public PrivacidadCorreo PrivacidadCorreo { get; set; }
        public Genero Genero { get; set; }
        public int Edad { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public bool Activo { get; set; }

        public int Dni { get; set; }
        public string Domicilio  { get; set; }
        public Nacionalidad Nacionalidad { get; set; }
        public int Telefono { get; set; }
        public string Descripcion { get; set; }
        public byte[]? FotoPerfil { get; set; }

        public string Clave { get; set; }
        public string ConfirmarClave { get; set; }
        public bool Restablecer { get; set; }
        public bool Confirmado { get; set; }
        public string Token { get; set; }

        public List<CursoEstudiante> CursosEstudiantes { get; set; } = new List<CursoEstudiante>();
        public List<ExamenEstudiante> ExamenEstudiantes { get; set; } = new List<ExamenEstudiante>();
    }
}

StudentPortal/Entities/Perfil.cs
using StudentPortal.Models;

namespace StudentPortal.Entities
{
    public class Perfil
    {
        public int Id { get; set; }
        public string Nombre { get; set; }

        public virtual ICollection <Empleado> Empleados { get; set; }
    }
}

StudentPortal/Controllers/EstudianteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MimeKit;
using StudentPortal.Data;
using StudentPortal.Entities;
using StudentPortal.Models;
using StudentPortal.Services;


namespace StudentPortal.Controllers
{

    public class EstudianteController: Controller
    {
        private readonly EstudianteService _estudianteService;
        private readonly UtilService _utilService;
        private readonly EmailService _emailService;
        private readonly IWebHostEnvironment _env;
        const string SessionUserId = "_UserId";
        const string SessionUserName = "_UserName";
        const string SessionUserToken = "_UserToken";

        public EstudianteController(EstudianteService estudianteService, UtilService utilService, EmailService emailService, IWebHostEnvironment env)
        {
            _estudianteService = estudianteService;
            _utilService = utilService;
            _emailService = emailService;
            _env = env;
        }

        [HttpGet]
        public ViewResult Login() {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(string correo, string clave) {
            EstudianteDto? usuario = await _estudianteService.ValidarAsync(correo, _utilService.ConvertirSHA256(clave));

            if (usuario != null)
            {
                if (!usuario.Confirmado)
                {
                    ViewBag.Mensaje = $"Falta confirmar su cuenta. Se le envio un correo a {correo}";
                }
                else if (usuario.Restablecer)
                {
                    ViewBag.Mensaje = $"Se ha solicitado restablecer su cuenta, por favor revise su bandeja del correo {correo}";
                }
                else {
                    if (usuario.Token != null) {
                        //Crear sesion para el usuario logueado
                        HttpContext.Session.SetInt32(SessionUserId, usuario.EstudianteId);
                        HttpContext.Session.SetString(SessionUserToken, usuario.Token.ToString());
                    }

                    return RedirectToAction("Index", "Home");
                }
            }
            else {
                ViewBag.Mensaje = "No se encontraron coincidencias";
            }

            return View();
        }

        [HttpPost]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ViewResult Registrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<ViewResult> Registrar(EstudianteDto usuario) {
            if (usuario.Clave != usuario.ConfirmarClave) {
                //TODO: Use Validation
                ViewBag.Nombre = usuario.Nombre;
                ViewBag.Correo = usuario.Correo;
                ViewBag.Mensaje = "Las contraseñas no coinciden";

                return View();
            }

            var estudiante = await _estudianteService.ObtenerPorCorreoAsync(usuario.Correo);
            if (estudiante == null) {
                usuario.Clave = _utilService.ConvertirSHA256(usuario.Clave);
                usuario.Token = _utilService.GenerarToken();
                usuario.Restablecer = false;
                usuario.Confirmado = false;

                //Confirmar cuenta
                if (await _estudianteService.RegistrarAsync(usuario)){
                    string rutaArchivoHtml = Path.Combine(_env.ContentRootPath, "Template", "Confirmar.html");
                    string contenido = await System.IO.File.ReadAllTextAsync(rutaArchivoHtml);
                    
                    //Generar url
                    string baseUrl = $"{Request.Scheme}://{Request.Host.Host}:{Request.Host.Port}/Usuario/Confirmar?token={usuario.Token}";


                    CorreoDto correoDto = new CorreoDto()
                    {
                        Para = usuario.Correo,
                        Asunto = "Correo de Confirmación",
                        Contenido = string.Format(contenido, usuario.Nombre, baseUrl)
                    };
                    bool enviado = _emailService.Enviar(correoDto);

                    ViewBag.Creado = true;
                    ViewBag.Mensaje = $"Su cuenta ha sido creada. Hemos enviado un mensaje al correo {usuario.Correo} para confirmar su cuenta";
                }else {
                    ViewBag.Mensaje = "No se pudo crear su cuenta";
                }
            }else{
                ViewBag.Mensaje = "El correo ya se encuentra registrado";
            }

            return View();
        }

        [HttpGet]
        public async Task<ViewResult> Confirmar(string token) {
            ViewBag.Respuesta = await _estudianteService.ConfirmarAsync(token);
            return View();
        }

        [HttpGet]
        public ViewResult Restablecer() { 
            return View(); 
        }

        [HttpPost]
        public async Task<ViewResult> Restablecer(string correo) {
            EstudianteDto? usuario = await _estudianteService.ObtenerPorCorreoAsync(correo);
            ViewBag.Correo = correo;
            if (usuario != null) {
                bool respuesta = await _estudianteService.RestablecerClaveAsync(1, usuario.Clave, usuario.Token);

                if (respuesta)
                {
                    string rutaArchivoHtml = Path.Combine(_env.ContentRootPath, "Template", "Restablecer.html");
                    string contenido = await System.IO.File.ReadAllTextAsync(rutaArchivoHtml);

                    //Generar url
                    string baseUrl = $"{Request.Scheme}://{Request.Host.Host}:{Request.Host.Port}/Usuario/Actualizar?token={usuario.Token}";

                    CorreoDto correoDto = new CorreoDto()
                    {
                        Para = correo,
                        Asunto = "Restablecer Contraseña",
                        Contenido = string.Format(contenido, usuario.Nombre, baseUrl)
                    };
                    bool enviado = _emailService.Enviar(correoDto);

                    ViewBag.Restablecido = true;
                    ViewBag.Mensaje = "Su contraseña fue restablecida, le enviamos un mensaje a su correo para restablecer.";
                }
                else {
                    ViewBag.Mensaje = "No se pudo restablecer la cuenta";
                }
            }
            else {
                ViewBag.Mensaje = "No se encontraron coincidencias con el correo";
            }
            return View(); 
        }

        [HttpGet]
        public ViewResult Actualizar(string token) {
            ViewBag.Token = token;

            return View();
        }

        [HttpPost]
        public async Task<ViewResult> Actualizar(string token, string clave, string confirmarClave) {
            ViewBag.Token = token;

            if (clave != confirmarClave) {
                ViewBag.Mensaje = "Las contraseñas no coinciden";

                return View();
            }
            
            bool respuesta = await _estudianteService.RestablecerClaveAsync(0, _utilService.ConvertirSHA256(clave), token);
            if (respuesta)
            {
                ViewBag.Restablecido = true;
            }
            else {
                ViewBag.Mensaje = "No se pudo actualizar";
            }

            return View();
        }


        [HttpGet]
        public async Task<ActionResult> Perfil(int id) { 
            var estudiante = await _estudianteService.ObtenerPorIdAsync(id);
            int? userId = HttpContext?.Session.GetInt32("_UserId");
            
            if (estudiante == null || userId == null ) {
                return RedirectToAction("Index","Home");
            }
            
            ViewBag.Id = userId;
            return View(estudiante);
        }

        [HttpPost]
        public async Task<ActionResult> Perfil(int id, EstudianteDto estudiante)
        {
            if (ModelState.IsValid)
            {
                var resultado = await _estudianteService.ActualizarAsync(id, estudiante);
                if (resultado) {
                    ViewBag.Mensaje = "Se actualizó los datos correctamente";
                }
                else {
                    ViewBag.Mensaje = "Ocurrió un error al actualizar los datos.";
                }
            }
            else {
                foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            return View(estudiante);
        }
    }
}

StudentPortal/Views/Estudiante/Actualizar.cshtml
@{
    ViewData["Title"] = "Actualizar";
}

<div class="row justify-content-center mt-5">
    @* Form *@
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                <h3 class="text-center">Restablecer Cotraseña</h3>
            </div>
            <div class="card-body">
                @if (ViewBag.Restablecido == null)
                {
                    <form asp-action="Actualizar" asp-controller="Usuario" method="post">
                        <input type="hidden" name="token" value="@ViewBag.Token"/>
                        
                        <div class="form-group mt-3">
                            <label for="clave">Ingresa una nueva contraseña</label>
                            <input type="password" class="form-control" id="clave" name="clave" placeholder="Ingrese su clave" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="confirm_clave">Confirmar Clave</label>
                            <input type="password" class="form-control" id="confirm_clave" name="confirmarClave" placeholder="Reingrese su clave" required>
                        </div>
                        @* Alert *@
                        @if (ViewBag.Mensaje != null)
                        {
                            <div class="alert alert-warning mt-3" role="alert">
                                <p>@ViewBag.Mensaje</p>
                            </div>
                        }
                        <div class="mb-3 d-grid gap-2">
                            <button type="submit" class="btn btn-primary mt-4">Cambiar contraseña</button>
                        </div>
                    </form>
                }
                else
                {
                    <div class="alert alert-success mt-3" role="alert">
                        <p>Su contraseña fue restablecida, ahora puede ingresar a su cuenta con su nueva clave.</p>
                        <a class="btn btn-success" asp-action="Login" asp-controller="Usuario">Ingresar</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

StudentPortal/Views/Estudiante/Confirmar.cshtml
@{
    ViewData["Title"] = "Confirmar";
}
<div class="container">
    @if ((bool)ViewBag.Respuesta)
    {
        <div class="alert alert-success w-50 mx-auto">
            <p>
                <b>Listo!</b>&nbsp; 
                Su cuenta fue confirmada. Ahora puede acceder
            </p>
            <p class="text-center">
                <a class="btn btn-success ms-2" asp-action="Login" asp-controller="Usuario">Ingresar</a>
            </p>
        </div>
    }
    else
    {
        <div class="alert alert-danger w-50 mx-auto">
            <p>No se pudo confirmar el correo.</p>
        </div>
    }
</div>

StudentPortal/Views/Estudiante/Login.cshtml
@{
    ViewData["Title"] = "Login";
}
<div class="row justify-content-center mt-5">
    @* Form *@
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                <h3 class="text-center">Login</h3>
            </div>
            <div class="card-body">
                <form asp-action="Login" asp-controller="Estudiante" method="post">
                    <div class="form-group">
                        <label for="correo">Correo electrónico</label>
                        <input type="email" class="form-control" id="correo" name="correo" placeholder="Ingrese su correo" required>
                    </div>

                    <div class="form-group mt-3">
                        <label for="clave">Clave</label>
                        <input type="password" class="form-control" id="clave" name="clave" placeholder="Ingrese su clave" required>
                    </div>
                    @* Alert *@
                    @if (ViewBag.Mensaje != null)
                    {
                        <div class="alert alert-warning my-2" role="alert">
                            @ViewBag.Mensaje
                        </div>
                    }
                    <div class="mb-3 d-grid gap-2">
                        <button type="submit" class="btn btn-success mt-4">Iniciar Sesión</button>
                        <a class="btn btn-link" asp-action="Registrar" asp-controller="Usuario">¿No tienes una cuenta? Registrate</a>
                        <a class="btn btn-link" asp-action="Restablecer" asp-controller="Usuario">¿Haz olvidado tu contraseña?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

StudentPortal/Views/Estudiante/Perfil.cshtml
@using StudentPortal.Models
@model EstudianteDto
@{
    ViewData["Title"] = "Mis Datos";
}

<div class="container">
    <div class="row mt-3">
        <div class="col-3">
            @await Html.PartialAsync("_MenuPartialView")
        </div>
        <div class="col-9 p-3">
            <div class="row align-items-center mb-2">
                <h3>Mis Datos</h3>
            </div>
            <form asp-action="Perfil" asp-controller="Estudiante" method="post" enctype="multipart/form-data">
                <input name="id" value="@ViewBag.Id" hidden />
                @*Image*@
                <div class="text-center">
                    <div class="position-relative d-inline-block">
                        @if (Model.FotoPerfilBytes != null)
                        {
                            <img src="data:image/jpeg;base64,@Convert.ToBase64String(Model.FotoPerfilBytes)" alt="Logo" width="200" height="200" class="rounded-circle">
                        }else{
                            <img src="~/images/default_estudiante.jpg" alt="Logo" width="200" height="200" class="rounded-circle">
                        }
                        <label class="btn btn-primary position-absolute rounded-circle" style="bottom: 10px; right: 10px;">
                            <input type="file" name="FotoPerfil" class="d-none">
                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus mb-1" viewBox="0 0 16 16">
                                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4" />
                            </svg>
                        </label>
                    </div>
                </div>
                @**@
                <div class="row mb-2">
                    <div class="form-group col-4">
                        <label asp-for="Username">Username:</label>
                        <div class="input-group">
                            <span class="input-group-text" id="basic-addon1">@@</span>
                            <input asp-for="Username" class="form-control" aria-label="Username" aria-describedby="basic-addon1">
                        </div>
                    </div>
                    <div class="form-group col-4">
                        <label asp-for="Nombre">Nombre:</label>
                        <input asp-for="Nombre" class="form-control" readonly />
                        <span asp-validation-for="Nombre" class="text-danger"></span>
                    </div>
                    <div class="form-group col-4">
                        <label asp-for="Apellido">Apellido:</label>
                        <input asp-for="Apellido" class="form-control" readonly />
                        <span asp-validation-for="Apellido" class="text-danger"></span>
                    </div>
                </div> 
                <div class="row mb-2">
                    <div class="form-group col-4">
                        <label asp-for="FechaNacimiento">Fecha de Nacimiento:</label>
                        <input asp-for="FechaNacimiento" class="form-control" readonly />
                        <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                    </div>
                    <div class="form-group col-4">
                        <label asp-for="Dni">DNI:</label>
                        <input asp-for="Dni" ty class="form-control" readonly/>
                        <span asp-validation-for="Dni" class="text-danger"></span>
                    </div>
                    <div class="form-group col-4">
                        <label asp-for="Nacionalidad">Seleccione su nacionalidad:</label>
                        <select asp-for="Nacionalidad" class="form-select">
                            <option value="">Seleccione un país</option>
                            <option value="0">Argentina</option>
                            <option value="1">Estados Unidos</option>
                            <option value="2">Bolivia</option>
                            <option value="3">Brasil</option>
                            <option value="4">Canadá</option>
                            <option value="5">Chile</option>
                            <option value="6">Colombia</option>
                            <option value="7">Ecuador</option>
                            <option value="8">Paraguay</option>
                            <option value="9">Perú</option>
                            <option value="10">Uruguay</option>
                            <option value="11">Venezuela</option>
                        </select>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="form-group col-4">
                        <label asp-for="Telefono">Teléfono:</label>
                        <input asp-for="Telefono" class="form-control" type="tel" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>
                    <div class="form-group col-8">
                        <label asp-for="Correo">Correo:</label>
                        <input asp-for="Correo" class="form-control" type="email" />
                        <span asp-validation-for="Correo" class="text-danger"></span>
                    </div>
                </div>
                <div class="row mb-2">
                    <div class="form-group col-4">
                        <label asp-for="Domicilio">Domicilio  <span class="text-muted">(Opcional)</span>:</label>
                        <input asp-for="Domicilio" class="form-control" />
                        <span asp-validation-for="Domicilio" class="text-danger"></span>
                    </div>
                    <div class="form-group col-4">
                        <label asp-for="Genero">Seleccione su genero:</label>
                        <select asp-for="Genero" class="form-select">
                            <option value="">Seleccione un genero</option>
                            <option value="0">Masculino</option>
                            <option value="1">Femenino</option>
                            <option value="2">No Especificado</option>
                        </select>
                    </div>
                    <div class="form-group col-4">
                        <label asp-for="PrivacidadCorreo" class="d-flex align-items-center gap-1 px-1 w-100">
                            Seleccione la privacidad:   
                            <svg xmlns="http://www.w3.org/2000/svg"
                                 data-bs-toggle="popover" data-bs-title="Privacidad de Correo" data-bs-content="Indica cuando el correo es visible para los usuarios de la plataforma"
                                 width="16" height="16" fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16">
                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16" />
                                <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286m1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94" />
                            </svg>
                        </label>
                        <select asp-for="PrivacidadCorreo" class="form-select">
                            <option value="">Seleccione una privacidad</option>
                            <option value="0">Mostrar a todos</option>
                            <option value="1">Ocultar a todos</option>
                            <option value="2">Mostrar solo a los participantes del curso</option>
                        </select>
                    </div>
                </div>
                <div>
                    <label asp-for="Descripcion" class="form-label">Descripción <span class="text-muted">(Opcional)</span>:</label>
                    <textarea asp-for="Descripcion" class="form-control" rows="3"></textarea>
                </div>

                @* Alert *@
                @if (ViewBag.Mensaje != null)
                {
                    <div class="alert alert-warning my-2" role="alert">
                        @ViewBag.Mensaje
                    </div>
                }

                <div class="mb-3 d-grid gap-2">
                    <button type="submit" class="btn btn-success mt-4">Actualizar Datos</button>
                </div>
            </form>
        </div>
    </div>
</div>

StudentPortal/Views/Estudiante/Registrar.cshtml
@{
    ViewData["Title"] = "Registrar";
}
<div class="row justify-content-center mt-5">
    @* Form *@
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                <h3 class="text-center">Registrar</h3>
            </div>
            <div class="card-body">
                    <form asp-action="Registrar" asp-controller="Usuario" method="post">
                        <div class="form-group">
                            <label for="nombre">Nombre</label>
                            <input type="text" class="form-control" id="nombre" value="@(ViewBag.Nombre != null ? ViewBag.Nombre : "")" name="Nombre" placeholder="Ingrese su nombre" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="correo">Correo electrónico</label>
                            <input type="email" class="form-control" id="correo" value="@(ViewBag.Correo != null ? ViewBag.Correo : "")" name="Correo" placeholder="Ingrese su correo" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="clave">Clave</label>
                            <input type="password" class="form-control" id="clave" name="Clave" placeholder="Ingrese su clave" required>
                        </div>
                        <div class="form-group mt-3">
                            <label for="confirm_clave">Confirmar Clave</label>
                            <input type="password" class="form-control" id="confirm_clave" name="ConfirmarClave" placeholder="Reingrese su clave" required>
                        </div>
                        @* Alert *@
                        @if (ViewBag.Mensaje != null)
                        {
                            var alertClass = ViewBag.Creado == null ? "alert-warning" : "alert-success";
                            <div class="alert @alertClass mt-3" role="alert">
                                <p>@ViewBag.Mensaje</p>
                            </div>

                            @*<script>
                                // Mostrar el alert
                                document.addEventListener('DOMContentLoaded', function () {
                                    var alert = document.getElementById('alert');
                                    alert.style.display = 'block'; // Muestra el alert

                                    // Ocultar después de 5 segundos
                                    setTimeout(function () {
                                        alert.style.display = 'none'; // Oculta el alert
                                    }, 5000);
                                });
                            </script>*@
                        }
                        <div class="mb-3 d-grid gap-2">
                            <button type="submit" class="btn btn-primary mt-4">Registrar</button>
                            <a class="btn btn-link" asp-action="Login" asp-controller="Usuario">¿Ya tienes una cuenta? Inicia sesión</a>
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>

StudentPortal/Views/Estudiante/Restablecer.cshtml
@{
    ViewData["Title"] = "Restablecer";
}

<div class="row justify-content-center mt-5">
    @* Form *@
    <div class="col-5">
        <div class="card">
            <div class="card-header">
                <h3 class="text-center">Restablecer Cuenta</h3>
            </div>
            <div class="card-body">
                @if (ViewBag.Restablecido == null)
                {
                    <form asp-action="Restablecer" asp-controller="Usuario" method="post">
                        <p>Ingrese su dirección de correo electrónico y le enviaremos un enlace para restablecer su contraseña.</p>
                        <div class="form-group mt-3">
                            <label for="correo">Correo electrónico</label>
                            <input type="email" class="form-control" id="correo" name="correo" placeholder="Ingrese su correo" required>
                        </div>
                        @* Alert *@
                        @if (ViewBag.Mensaje != null)
                        {
                            <div class="alert alert-warning mt-3" role="alert">
                                <p>@ViewBag.Mensaje</p>
                            </div>
                        }
                        <div class="mb-3 d-grid gap-2">
                            <button type="submit" class="btn btn-primary mt-4">Restablecer</button>
                            <a class="btn btn-link" asp-action="Login" asp-controller="Usuario">Volver</a>
                        </div>
                    </form>
                }
                else
                {
                    <div class="alert alert-success mt-3" role="alert">
                        <p>Su contraseña fue restablecida, le enviamos un mensaje a su correo para restablecer.</p>
                        <a class="btn btn-success" asp-action="Login" asp-controller="Usuario">Ingresar</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>